import { Career, ArcProgress, RunResult } from "./types";
import { reflect, reflectArc, playStyleLabel } from "./reflect";
import { formatClock } from "./scenario";
import { whatBroke, buildEnergyTimeline } from "./arc";

/** A saved debrief for export and run history (localStorage only - no accounts). */
export interface SavedRunRecord {
  id: string;
  careerId: string;
  careerTitle: string;
  completedAt: string;
  arcComplete: boolean;
  daysPlayed: number;
  /** One-line pattern headline for list views. */
  patternSummary: string;
  finalEnergy: number;
  playStyle: string;
  report: string;
}

/** Plain-text debrief suitable for download, email, or counselor review. */
export function formatDebriefReport(
  career: Career,
  result: RunResult,
  arcProgress?: ArcProgress | null,
): string {
  const arcComplete = arcProgress?.complete ?? false;
  const arcRefl =
    arcComplete && arcProgress
      ? reflectArc(career, arcProgress.completedDays)
      : null;
  const reflection = arcRefl ?? reflect(career, result);

  const lines: string[] = [
    "A DAY IN",
    "Career Simulation Report",
    "========================",
    "",
    `Career: ${career.title}`,
    `Completed: ${new Date().toISOString().slice(0, 10)}`,
  ];

  if (arcProgress && arcProgress.completedDays.length > 0) {
    lines.push(
      `Arc: day ${result.arcDay ?? arcProgress.completedDays.length} of ${arcProgress.totalDays}${arcComplete ? " (complete)" : ""}`,
    );
  }

  lines.push(
    "",
    "PATTERN",
    "-------",
    reflection.pattern,
    "",
    "YOUR DAY, BEAT BY BEAT",
    "--------------------",
    ...reflection.moments.map((m) => `· ${m}`),
  );

  const timeline = result.energyTimeline ?? buildEnergyTimeline(career, result);
  const broke = whatBroke(career, timeline);
  if (broke.length > 0) {
    lines.push("", "WHAT BROKE (ENERGY)", "-------------------", ...broke);
  }

  if (arcRefl?.energyArc) {
    lines.push("", "ACROSS THE ARC", "--------------", arcRefl.energyArc);
  }

  lines.push(
    "",
    "TENSIONS",
    "--------",
    ...reflection.leans
      .filter((l) => l.count > 0)
      .map(
        (l) =>
          `· ${l.tension.label}: leaned ${l.score >= 0 ? l.tension.poleA : l.tension.poleB}`,
      ),
    "",
    "WORTH WEIGHING",
    "--------------",
    ...reflection.fitSignals.map((s) => `· ${s}`),
    "",
    "ADJACENT CAREERS TO TRY",
    "-----------------------",
    ...reflection.adjacent.map((a) => `· ${a.careerId}: ${a.reason}`),
    "",
    "CAVEAT",
    "------",
    reflection.caveat,
    "",
    `Final energy: ${result.finalState.energy}/100 · ended ${formatClock(result.finalState.clock)}`,
    "",
    "Generated by A Day In · a-day-in",
  );

  return lines.join("\n");
}

export function createSavedRunRecord(
  career: Career,
  result: RunResult,
  arcProgress?: ArcProgress | null,
): SavedRunRecord {
  const arcComplete = arcProgress?.complete ?? false;
  const arcRefl =
    arcComplete && arcProgress
      ? reflectArc(career, arcProgress.completedDays)
      : null;
  const reflection = arcRefl ?? reflect(career, result);
  return {
    id: `${career.id}-${Date.now()}`,
    careerId: career.id,
    careerTitle: career.title,
    completedAt: new Date().toISOString(),
    arcComplete,
    daysPlayed: arcProgress?.completedDays.length ?? 1,
    patternSummary: reflection.pattern,
    finalEnergy: result.finalState.energy,
    playStyle: playStyleLabel(career, result),
    report: formatDebriefReport(career, result, arcProgress),
  };
}
